import { NextResponse } from 'next/server';
import { backendStore } from '@/lib/backendStore';

export async function GET() {
  try {
    return NextResponse.json({
      success: true,
      count: backendStore.exportReports.length,
      reports: backendStore.exportReports
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: 'Failed to retrieve export reports archive' },
      { status: 500 }
    );
  }
}

export async function POST(request) {
  try {
    const body = await request.json().catch(() => ({}));
    const operatorName = body.operatorName || 'Dr. Rajesh Kumar (SEOC Director)';
    const operatorRole = body.operatorRole || 'ADMIN';
    const notes = body.notes || 'Routine disaster management telemetry and platform audit.';

    // Generate comprehensive usage analysis
    const logs = [...backendStore.usageLogs];
    const shelters = [...backendStore.shelters];
    const sosAlerts = [...backendStore.sosAlerts];
    const zones = [...backendStore.zones];

    const totalCapacity = shelters.reduce((acc, s) => acc + (s.totalCapacity || 0), 0);
    const currentOccupancy = shelters.reduce((acc, s) => acc + (s.currentOccupancy || 0), 0);

    const functionUsageCounts = {};
    const roleCounts = { ADMIN: 0, STAFF: 0, CITIZEN: 0 };
    const userActivityMap = {};

    logs.forEach((log) => {
      functionUsageCounts[log.functionName] = (functionUsageCounts[log.functionName] || 0) + 1;
      if (roleCounts[log.userRole] !== undefined) {
        roleCounts[log.userRole]++;
      }
      if (!userActivityMap[log.userId]) {
        userActivityMap[log.userId] = {
          userId: log.userId,
          userName: log.userName,
          userRole: log.userRole,
          totalActions: 0,
          functionsUsed: new Set(),
          lastActive: log.timestamp
        };
      }
      userActivityMap[log.userId].totalActions++;
      userActivityMap[log.userId].functionsUsed.add(log.functionName);
    });

    const userSummaryList = Object.values(userActivityMap).map((u) => ({
      userId: u.userId,
      userName: u.userName,
      userRole: u.userRole,
      totalActions: u.totalActions,
      functionsUsed: Array.from(u.functionsUsed),
      lastActive: u.lastActive
    }));

    // Generate CSV String representation of usage
    const csvHeaders = 'LogID,Timestamp,UserID,UserName,Role,FunctionName,Action,Route,MetadataDetails\n';
    const csvRows = logs
      .map((l) => {
        const metaStr = JSON.stringify(l.metadata || {}).replace(/"/g, '""');
        return `"${l.id}","${l.timestamp}","${l.userId}","${l.userName}","${l.userRole}","${l.functionName}","${l.action}","${l.route}","${metaStr}"`;
      })
      .join('\n');
    const csvContent = csvHeaders + csvRows;

    // Generate Markdown Executive Report
    const markdownReport = `# DISHA Geo-Intelligence Platform: User Activity & Operations Audit Report
**Generated At:** ${new Date().toUTCString()}
**Generated By:** ${operatorName} (${operatorRole})
**Report ID:** DISHA-REP-2026-${String(backendStore.exportReports.length + 1).padStart(3, '0')}
**Security Classification:** SEOC RESTRICTED / HUMANITARIAN AUDIT

---

## 1. Executive Telemetry Summary
- **Total User Operations Tracked:** ${logs.length}
- **Distinct Active Users / Responders:** ${userSummaryList.length}
- **Role Breakdown:**
  - Admin (SEOC): ${roleCounts.ADMIN || 0}
  - Staff (NDRF / Field): ${roleCounts.STAFF || 0}
  - Citizen / Community: ${roleCounts.CITIZEN || 0}
- **Active Hazard Red-Zones:** ${zones.filter((z) => z.riskLevel === 'RED').length}
- **Shelters & Relocation Staging Capacity:** ${currentOccupancy.toLocaleString()} / ${totalCapacity.toLocaleString()} beds occupied (${Math.round((currentOccupancy / totalCapacity) * 100)}%)
- **Active Citizen SOS Distress Beacons:** ${sosAlerts.length} (${sosAlerts.filter((s) => s.status === 'DISPATCHED').length} dispatched, ${sosAlerts.filter((s) => s.status === 'RESCUED').length} rescued)

---

## 2. Platform Function Usage Frequency
| Function Name | Invocations | Primary User Category | Description |
|---|---|---|---|
${Object.entries(functionUsageCounts)
  .map(
    ([fn, count]) =>
      `| \`${fn}\` | **${count}** | Multi-Role | Operations telemetry logged via DISHA gateway |`
  )
  .join('\n')}

---

## 3. User Activity & Function Audit Log
| User ID | User Name | Role | Total Actions | Functions Utilized | Last Active |
|---|---|---|---|---|---|
${userSummaryList
  .map(
    (u) =>
      `| **${u.userId}** | ${u.userName} | \`${u.userRole}\` | ${u.totalActions} | ${u.functionsUsed.join(', ')} | ${new Date(u.lastActive).toLocaleTimeString()} |`
  )
  .join('\n')}

---

## 4. Operational Notes
${notes}
`;

    // Persist to export reports database
    const savedRecord = backendStore.createExportReport({
      generatedBy: operatorName,
      generatedByRole: operatorRole,
      title: `DISHA User Operations Audit [${new Date().toISOString().slice(0, 10)}]`,
      format: 'JSON + CSV + MD',
      summary: `Export of ${logs.length} events across ${userSummaryList.length} distinct users and ${Object.keys(functionUsageCounts).length} functions.`,
      stats: {
        totalEventsTracked: logs.length,
        uniqueUsers: userSummaryList.length,
        functionBreakdown: functionUsageCounts,
        roleBreakdown: roleCounts,
        shelterBufferRemaining: totalCapacity - currentOccupancy
      }
    });

    return NextResponse.json({
      success: true,
      message: 'Usage report generated and archived in database',
      reportRecord: savedRecord,
      jsonData: {
        platform: 'DISHA Geo-Intelligence Platform',
        reportId: savedRecord.id,
        generatedAt: savedRecord.generatedAt,
        operator: { name: operatorName, role: operatorRole },
        kpis: {
          totalEvents: logs.length,
          uniqueUsers: userSummaryList.length,
          totalSafeCapacity,
          currentOccupancy,
          availableBuffer: totalCapacity - currentOccupancy,
          sosAlertsCount: sosAlerts.length
        },
        functionBreakdown: functionUsageCounts,
        roleBreakdown: roleCounts,
        users: userSummaryList,
        logs
      },
      csvContent,
      markdownReport
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: 'Failed to generate export report' },
      { status: 500 }
    );
  }
}
